# 语言文件[可选 中文简体:zh_CN]
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 多久异步同步一次数据并刷新排行榜 单位秒(改动需重启生效)
# 如果设置为0,不会执行同步操作
task: 300

# 排行榜是否过滤 op true过滤, false不过滤
isOp: false